
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
#      SPRING_PROFILES_ACTIVE: dev
      # 直接把帳密寫在此
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Jackul6fupck6!
    ports:
      - "8080:8080"
#    depends_on:
#      - db

volumes:
  db_data: